GET localhost:7070/api/poem


###
POST localhost:7070/api/poem
Content-Type: application/json

{
  "title": "Mr. Girth",
  "style": "epic",
  "poem": "Sing O grand muse, sing as thy life depended on the..."
}

###
PUT localhost:7070/api/poem/3
Content-Type: application/json

{
  "title": "Mr. Girth",
  "style": "epic",
  "poem": "Sing O grand muse, sing as thy life depended on the..."
}